### PR TITLE
New themes

### PR DESCRIPTION
**Pull request by jorgenqv**
Hello,
I made two themes from some CC licensed SVG graphics I found at http://www.3quarks.com/en/SVGClock/ and on http://commons.wikimedia.org/wiki/File:Station_Clock.svg
Hope I made the themes correct and I did everything correct here at Github, this is my first new file pull request ever :-)
/Jörgen

### CODE REVIEW

**Comment by Cobinja** [comment]
While the WallClock theme is perfectly fine, I think the Railway one deserves a little less space between the image and the border.

**Comment by jorgenqv** [comment]
Thank you Lars, and yes I totally agree. The reason the Railway one is smaller is that the clock pointers for this theme needs to be stretch out longer on the clock face, also the wall one would need slightly longer ones.  But I have no idea how that could be done, not affecting the look of the other themes. Or perhaps larger default clock pointers is alight?

**Comment by Cobinja** [comment]
You could decrease the overall width and height of the images, leaving the content at the same size. Then adjust the size entry in metadata.json accordingly.

**Comment by jorgenqv** [comment]
Ahh, I didn't get how that works, tried to change the values in metadata.json but only got the clock face up in the left corner. But I will give it a go again! :) Will get back to you, thanks!

**Comment by Cobinja** [comment]
I use the size value to determine the scaling factor between the svg images and the displayed desklet size.

**Comment by jorgenqv** [comment]
Did some work on the themes and now I know how it works :) Also added icon.png used by Cinnamon Desklet Manager and a short hints text about working themes in the readme.

**Comment by Cobinja** [comment]
Looks fine now.
Except for the location of icon.png, you missed the ".de" in the folder name.

**Comment by jorgenqv** [comment]
Thank you for taking time to look at my theme work. I can not upload the png file there, if I enter the directory  "analog-clock@cobinja.de" and click on Upload file the last ".de" part is cut of and a new directory is created, strange...

**Comment by Cobinja** [comment]
To be honest, I don't really like the BigBen theme, especially the background. Looks as if it's the scan of the cutout of a photo.
About icon.png: Just do it locally on your machine, do the commit and push the branch. Works perfectly well.

**Comment by jorgenqv** [comment]
Yeah, you’re right, it is perhaps a bit too much to have on your desktop and is actually a CC image from Wikimedia Commons, it also got a bit dull in the colours when converted to SVG. Thanks for your honesty! :) Will try to set up git on my local machine.

**Comment by jorgenqv** [comment]
Done, worked fine as you suggested.

**Comment by muzena** [comment]
@Cobinja 
Can you upload to spicies page version with new themes.

**Comment by Cobinja** [comment]
I will include them in the new version I am currently preparing

**Pull request merged**
